version: '3'

services:
  auth_server:
    image: authserver:latest
    build: .
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - PORT=8100
      - PG_USER=helios
      - PG_PASSWORD=helios
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DB=bedb
    ports:
      - 8100:8100
  
  postgres:
    image: postgres:10.1-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_PASSWORD=helios
      - POSTGRES_USER=helios
      - POSTGRES_DB=bedb
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
