version: '3'

services:
  api_server:
    image: apiserver:latest
    build: .
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - PORT=8080
      - PG_USER=helios
      - PG_PASSWORD=helios
      - PG_HOST=127.0.0.1
      - PG_PORT=5432
      - PG_DB=bedb
    ports:
      - 8080:8080
  
  postgres:
    image: postgres:10.1-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_PASSWORD=helios
      - POSTGRES_USER=helios
      - POSTGRES_DB=bedb
    ports:
      - 5432:5432
